AllCops:
 TargetRubyVersion: 2.4

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 130

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
